travis:
  secure:
    BINSTAR_TOKEN: DQIbbFuKT/X4OpD6uZKig80s/aNIjV5w/BECQaFVdH53mNezlPvVTnyAyxodbgpdcyqY0YgPs+z+32w33S5elXY0uZYewKn4l/ZGs7bYXsu7hd3PKBXXdLwa4K+EtVKGJBGiD0Z2WV9LhnDj0rTJ6SrBrd24FH/vW7cpgXxuB6zMP9Uz7QMxAMcK6ORn4BoV6R8nOfX1oQOq+u3lTbcWJGdHBuemnjKrA9/O5z661k5gQIk+2abXxcBF/bEf+tYZuhz0AS/UtMwr8b6T4CSK5JDA20GZ3qAing+MUdg2w5TmEDhM+ic19iDwRJSEHfBVWWsrQCrcfMU4m9nx/ozTXWoR5UZUm+/0auSL7sZ2XW1X4pzLF6LElxN7i1czRrsgAHlpWGOVnCaMw7mJe9C4hUvAE38pzZz/DoRBvaahwpHGkWc1CN3rPCyv6kmmhRkK7kYsflFzM4F5mTbSsN64adCXBdgveudRHrjSG9fyrl59AaZr53iR5wDHZYwVy2XI+DTreVrikmQfDJn76DMt3mRuR5O+tyJyh6GLRKhVZoNIw/bFRT53cp2l9zAMF1B+FLMkaqAzMyVP5Od3L9wDsk+sA0lijNuMTB60Y4Air7HMBOGHDLsEBYeOCmXfMWlW7QbRROkaX+ZBK73vVSdpp3UHcxqscrslrJAGQSaw0ow=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
